FROM python:3.11-slim

WORKDIR /project

COPY requirements_ui.txt .
RUN pip install --no-cache-dir -r requirements_ui.txt

COPY . .

EXPOSE 7860

CMD ["streamlit", "run", "app/app.py", "--server.port", "7860", "--server.address", "0.0.0.0"]